'''
文字和二进制对应关系
ascii编码并不包含中文
GB-2312，国家信息委员会制作，80年，只包含国内
随后对其扩展制作GBK，包含了亚洲文字，95年
    都有局限性
unicode万国码
ucs2固定2个字节表示二进制和文字关系，2的16次方种可能
ucs4固定的4个字节表示，2的32次方种
    浪费空间
utf-8三个字节
对unicode进行压缩，尽可能少的来表示数据
python开发中再做文件存储或网络传播时不能直接用字符串而是
压缩成utf-8编码的字节，然后再来传输和存储
'''
name="羊妃"#字符串类型，unicode来存储，ucs4
file=open("name.txt","ab")
file.write(name.encode('utf-8'))
file.close()
#utf-8来存储b'\xe7\xbe\x8a\xe5\xa6\x83'